language: cpp

script:
  - cmake -P build.cmake

matrix:
  include:
    # OS X CMake
    - os: osx
      sudo: required
      osx_image: xcode8.2
      compiler:
        - clang
      env:
        - TOOL="cmake"
        - DESCRIPTION="OS X build/test via CMake"

before_install:
  - eval "${MATRIX_EVAL}"