language: cpp
script:
  - cmake -P build.cmake
# before_install:
#   - sudo apt-get install cmake

matrix:
  allow_failures:
    - env: ALLOW_FAILURES=true

  include:
    # linux version have unique dependencies, so we set them up individually
    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   services:
    #     - docker

    # OS X CMake
    - os: osx
     sudo: required
     osx_image: xcode8.2
     compiler:
       - clang
     env:
       - TOOL="cmake"
       - DESCRIPTION="OS X build/test via CMake"